### ISSUE TITLE
Not possible to make a new lexical entry

### ISSUE THREAD

**Issue by Mova-2020** [hdaSprachtechnologie/ukrajinet#3]
Die Möglichkeit, neue lexicalische Einträge einzusetzen, ist verloren. Es gibt die Warnung: "Bad Request
The browser (or proxy) sent a request that this server could not understand."
Gleichzeitig ist es unmöglich, einen lexicalischen Eintrag zu editieren.

**Comment by hdaSprachtechnologie** [comment]
problem solved
